### ISSUE TITLE
Pages Modifications

### ISSUE THREAD

**Issue by cvdbout** [dhrone/pydPiper#7] opened 2017-10-22 00:24 UTC
I think I've got my head round what each part of the pages file is doing, and I'm now attempting to edit.

This is my display right now (hd44780, i2c), however whenever I make changes to pages_lcd_20x4.py it isn't changing anything on the display.  Right now I'm trying to remove the TRK section at the bottom of the display from the canvases where its references, and the file shows that I've saved those changes, and this is the file in ExecStart.  Rebooting doesn't make a difference.

I assumed that as that's the file in execstart that it would be the one to edit?

![20171022_011247](https://user-images.githubusercontent.com/32599530/31856896-3ead8f96-b6c6-11e7-9a73-bd6c752942e4.jpg)

**Comment by dhrone** [comment] 2017-10-22 11:53
Yes you are editing the right file.  The problem is that the software is running within a Docker container so it cannot see the version of the file that you have edited.  Your ExecStart probably looks something like...

ExecStart=/usr/bin/docker run --network=host --privileged -v /var/log:/var/log:rw  dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver hd44780_i2c  --width 100 --height 32 --i2caddress 0x27 --timezone 'US/Eastern' --temperature fahrenheit --pages pages_lcd_20x4.py.

Try adding another -v command to it to allow the container to see the pydPiper directory.

ExecStart=/usr/bin/docker run --network=host --privileged **-v /home/volumio/pydPiper-v0.3-alpha:/app:ro** -v /var/log:/var/log:rw  dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver hd44780_i2c  --width 100 --height 32 --i2caddress 0x27 --timezone 'US/Eastern' --temperature fahrenheit --pages pages_lcd_20x4.py.

The format for -v is <dir_on_host>:<dir_in_container>:<permissions>.  So if you have placed pydPiper in a different directory, adjust <dir_on_host> to that directory.

I'd appreciate receiving any pages files you come up with.  I'm always looking to improve them.  I do have a specific question for you.  Right now, overly long lines scroll but the slow refresh of the LCDs makes this look less than perfect.  Do you prefer the scrolling, or would you prefer that scrolling be shut off?

**Comment by cvdbout** [comment] 2017-10-22 12:36
That's great - I did think that would be the case so attempted to change
the line myself but managed to make the whole thing unbootable instead.

I'll make the changes you suggested as soon as I do a clean install.

As soon as I get a page I'm happy with I'll share it here.

I like the scrolling - with very long song  titles it makes it easier to
read, but the wait time on the screen sometimes cuts off before the scroll
has finished, something I'm going to change. If possible though, it might
be easier to give people the option.  Even if that is possible though, I
understand that would mean writing an instruction file for how to make
changes and then allow docker to see the local file.

I've got a few ideas that I'd like to try and implement, if I can get them
to work I'll let you know.

On 22 Oct 2017 12:53 pm, "dhrone" <notifications@github.com> wrote:

Yes you are editing the right file. The problem is that the software is
running within a Docker container so it cannot see the version of the file
that you have edited. Your ExecStart probably looks something like...

ExecStart=/usr/bin/docker run --network=host --privileged -v
/var/log:/var/log:rw dhrone/pydpiper:latest python /app/pydPiper.py
--volumio --driver hd44780_i2c --width 100 --height 32 --i2caddress 0x27
--timezone 'US/Eastern' --temperature fahrenheit --pages pages_lcd_20x4.py.

Try adding another -v command to it to allow the container to see the
pydPiper directory.

ExecStart=/usr/bin/docker run --network=host --privileged *-v
/home/volumio/pydPiper-v0.3-alpha:/app:ro* -v /var/log:/var/log:rw
dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver
hd44780_i2c --width 100 --height 32 --i2caddress 0x27 --timezone
'US/Eastern' --temperature fahrenheit --pages pages_lcd_20x4.py.

The format for -v is <dir_on_host>:<dir_in_container>:. So if you have
placed pydPiper in a different directory, adjust <dir_on_host> to that
directory.

I'd appreciate receiving any pages files you come up with. I'm always
looking to improve them. I do have a specific question for you. Right now,
overly long lines scroll but the slow refresh of the LCDs makes this look
less than perfect. Do you prefer the scrolling, or would you prefer that
scrolling be shut off?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dhrone/pydPiper/issues/7#issuecomment-338471637>, or mute
the thread

**Comment by cvdbout** [comment] 2017-10-22 13:31
I've now made those changes, and got it to display a modified canvas once.  I made a further change to a canvas, saved the file, restarted docker and it's not loading the modified version now - changes still show in pydpiper.service and the pages file but are not being shown on the display.

I've commented out all sequences but one now, but its still scrolling through them all.

**Comment by dhrone** [comment] 2017-10-22 14:57
I think both of your problems (pages file and timezone) are related to the same issue.  I suspect you have not reloaded your systemd config.  Make sure that the copy of pydpiper.service located in /etc/systemd/system has the right settings.  Then you will need to force systemd to reload its configuration by issuing...

sudo systemctl daemon-reload

See...
[
https://serverfault.com/questions/700862/do-systemd-unit-files-have-to-be-reloaded-when-modified](url) 

Europe/London should be the correct setting.  A complete list of valid values is at...
[https://en.wikipedia.org/wiki/List_of_tz_database_time_zones](url)

**Comment by cvdbout** [comment] 2017-10-22 18:48
I've now got it showing the correct time zone, and this is the execstart in pydpiper.service

ExecStart=/usr/bin/docker run --network=host --privileged -v /home/volumio/**pydPiper-0.3-alpha**:/app:ro -v /var/log:/var/log:rw dhrone/pydpiper:latest python /app/pydPiper.py --volumio --driver hd44780_i2c --width 100 --height 32 --i2caddress 0x27 --timezone 'Europe/London' --temperature celcius --pages pages_lcd_20x4.py.

The part in bold may be of help to some people, as the default install location doesn't have v0.3, just 0.3.  Scratched my head over that one for a while!

**Comment by dhrone** [comment] 2017-10-22 19:04
Ahh.  Glad you caught the error.  Let me know how your page design goes.  I'll leave this issue open for the moment.

**Comment by cvdbout** [comment] 2017-10-22 23:08
Two last (hopefully anyway!) questions - within volumio there are 3 states - play, stop and pause.  Is that reflected anywhere on here?  I can only find play and stop, whereas if possible I'd like pause too (but no big deal if not, I've only had a quick glance through pydpiper.py, might be I'm not seeing it or I need to add that myself)

Also, the duration that the canvases are held for, what are those numbers?  I want to hold something for longer than just a few seconds but can't seem to find the magic number!

**Comment by dhrone** [comment] 2017-10-23 12:31
Currently the only states that pydPiper tracks are playing and stopped.  Paused == stopped.  Way back when I started this project, the distribution I was working with did not provide a paused status so it wasn't possible for me to distinguish between stopped and paused.   I will check to see if Volumio2 is exposing a paused status.  If yes, I'll see about adding it.

You may want to review the documentation for the pages file format in the docs directory.  Let me try to give a quick description here though.

Pages are displayed as part of a sequence of pages, sequence being composed of a set of canvases.  When a sequence is active, it starts displaying its canvases in order keeping each canvas on screen for <duration> seconds.  Each sequence has a Boolean value called a conditional that determines when the sequence should be active.   

Likewise, each canvas also has a conditional that determines whether that canvas should be displayed when its turn in the rotation comes up.  In the included pages_lcd_20x4.py file, there is a sequence called seqPlay that's conditional is db['state'] == 'play'.  So, this sequence becomes active when Volumio starts playing.  There are four canvases that are part of seqPlay.  The first three, playartist, playalbum, playtitle have conditionals that make them active when not playing from a webradio source.  The last, play_radio is active when Volumio is playing from a webradio source.  When a canvas is active and it's turn comes up, it is displayed for duration seconds.  So, if for instance you wanted to double the amount of time that the title is displayed, you could change duration for the playtitle canvas from 8 to 16.  

Hope this helps!

**Comment by cvdbout** [comment] 2017-10-23 13:25
That definitely helps, thank you!

I thought the number was in seconds, but it wasn't working correctly when I changed it.  I'll try again later.

I've got the canvases setup that I like, just looking into sequences now and what might work best for my needs.

The reason I asked about pause was I'd really like a pause sequence, that would display the pause canvas for x seconds then display the clock. Sort of like a timeout feature.  I've used the socketIO.emit feature with volumio2 which can toggle the states between play and pause - I can't remember if stop comes into it unless radio is playing though.

**Comment by cvdbout** [comment] 2017-10-25 20:31
Thanks for all your help, this is my display now. Very happy with it!

Play media screen, which holds for 30 seconds then volume, random (if enabled) and repeat (if enabled) screens scroll through 1 second each.
![20171025_141303](https://user-images.githubusercontent.com/32599530/32021213-a93ed444-b9ca-11e7-8886-80fee92de79e.jpg)
![20171025_141320](https://user-images.githubusercontent.com/32599530/32021214-a96242bc-b9ca-11e7-8484-3ad54b833a2c.jpg)
![20171025_141347](https://user-images.githubusercontent.com/32599530/32021215-a97c84b0-b9ca-11e7-89d3-82f1a2bb3b15.jpg)
![20171025_141348](https://user-images.githubusercontent.com/32599530/32021216-a9d865c8-b9ca-11e7-83cf-ab835e16ca33.jpg)

Starting splash screen
![20171025_141845](https://user-images.githubusercontent.com/32599530/32021218-aa108372-b9ca-11e7-97c5-14127da6213e.jpg)

Clock with no weather data
![20171025_141755](https://user-images.githubusercontent.com/32599530/32021217-a9f43f50-b9ca-11e7-99a5-0efa1c03cab6.jpg)

Clock with weather data
![20171025_142251](https://user-images.githubusercontent.com/32599530/32021219-aa35ea9a-b9ca-11e7-9fab-76fc59097267.jpg)

Radio screen showing elapsed time and clock, dislays for 30 seconds with volume screen showing for 1 second.
![20171025_192316](https://user-images.githubusercontent.com/32599530/32021220-aa5f0006-b9ca-11e7-8f19-c201bde947bb.jpg)
![20171025_192341](https://user-images.githubusercontent.com/32599530/32021221-aa85d5dc-b9ca-11e7-8506-f92709712152.jpg)

It might be worth noting that Volumio2 doesn't have repeat single as an option, not sure if there are plans to reintroduce it.

I was also having issues with the random and repeat screens showing randomly on boot and whenever play was switched between radio and MPD.  I resolved it by adding an extra conditional to the seqAnnounceRandom and seqAnnounceRepeat so they look like this now:

{
		'name':'seqAnnounceRandom',
		'canvases': [ { 'name':'showrandom', 'duration':2 } ],
		'conditional': "db['random'] != dbp['random'] and not db['actPlayer']=='webradio'",
		'minimum':2,
},
{
		'name':'seqAnnounceRepeat',
		'canvases': [ { 'name':'showrepeatall', 'duration':2 } ],
		'conditional': "db['repeat'] != dbp['repeat'] and not db['actPlayer']=='webradio'",
		'minimum':2,
},

**Comment by dhrone** [comment] 2017-10-28 13:14
Yes, this is caused by spurious changes of the random and repeat variables from Volumio when changing playing state.

Great job on your screens.  Should we close this issue out?

**Closed** 2017-10-28 14:13 UTC
